import { precacheAndRoute } from 'workbox-precaching';

// Precaching all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Web Push Notification Event Listener
self.addEventListener('push', function(event) {
  if (event.data) {
    try {
      const data = event.data.json();
      const title = data.title || 'Sanjivani Sync';
      const options = {
        body: data.body || 'You have a new emergency notification.',
        icon: data.icon || '/icon-192x192.png',
        badge: '/icon-192x192.png',
        data: data.data || { url: '/' },
        vibrate: [200, 100, 200, 100, 200, 100, 200]
      };

      event.waitUntil(self.registration.showNotification(title, options));
    } catch (e) {
      console.error('Error parsing push data', e);
    }
  }
});

// Notification Click Event Listener
self.addEventListener('notificationclick', function(event) {
  event.notification.close();
  
  const urlToOpen = event.notification.data.url || '/';

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Check if there is already a window/tab open with the target URL
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        // If so, just focus it.
        if (client.url.includes(urlToOpen) && 'focus' in client) {
          return client.focus();
        }
      }
      // If not, open a new window/tab.
      if (clients.openWindow) {
        return clients.openWindow(urlToOpen);
      }
    })
  );
});
